title: Rakshith Ramureddy
logo: assets/img/datamining.jpeg
description: MSc Business Analytics graduate with 4+ years’ experience in data analysis, stakeholder reporting, and technical support. Skilled in SQL, Power BI, Python, and government-style data governance. Delivered KPI dashboards, root cause analyses, and statutory data processing in both private and public-facing teams.
show_downloads: false
theme: jekyll-theme-hacker
