title: Rakshith Ramureddy
tagline: Data Analyst | MSc Business Analytics | SQL | Power BI | Python
description: >-
  MSc Business Analytics graduate with 4+ years of experience in data analysis, stakeholder reporting, and technical support.
  Skilled in SQL, Power BI, Python, and data governance. Delivered KPI dashboards, root cause analyses, and statutory reporting across sectors.

url: "https://rakshithramu.github.io"
baseurl: "/portfolio" # Must match your repository name

lang: en
timezone: Europe/London
theme: jekyll-theme-chirpy

avatar: /assets/img/datamining.jpeg
social:
  name: "Rakshith Ramureddy"
  email: rakshithreddy2012@gmail.com
  links:
    - https://www.linkedin.com/in/rakshithramu/
    - https://rakshith-ramureddy.github.io/portfolio/
    - https://github.com/rakshithramu

#google_analytics:
#  id: "" # Optional – Add your GA Tracking ID

theme_mode: auto # or 'light' or 'dark'

# Plugins required by Chirpy
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-paginate-v2
  - jekyll-include-cache
