title: Rakshith Ramureddy
logo: /assets/img/datamining.jpeg
description: >
  MSc Business Analytics graduate with 4+ years of experience in data analysis, stakeholder reporting, and technical support.
  Proficient in SQL, Power BI, Python, and public sector data governance. Delivered KPI dashboards, root cause analyses, and statutory data reporting in cross-functional teams.

# Site settings
url: "https://rakshithramureddy.github.io" # Replace with your GitHub Pages URL
baseurl: "" # Leave this blank unless using a project page

# Theme settings
remote_theme: mmistakes/minimal-mistakes
show_downloads: false

# Social media (optional)
author:
  name: "Rakshith Ramureddy"
  avatar: /assets/img/datamining.jpeg
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/rakshithramu/"
    - label: "Portfolio"
      url: "https://rakshith-ramureddy.github.io/portfolio/"
    - label: "GitHub"
      url: "https://github.com/yourusername"

plugins:
  - jekyll-include-cache
